### ISSUE TITLE
Option to select folder instead of file

### ISSUE THREAD

**Issue by achimmihca** [yasirkula/UnityNativeFilePicker#37]
I would like to have a file dialog to select a folder.
But this plugin only allows to select files (correct me if I am wrong)

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3 LTS
- Platform: Windows, Linux, macOS

**Comment by yasirkula** [comment]
You're correct. I have no knowledge if this is possible on iOS and on Android, picking folders won't return their raw filepaths since Storage Access Framework is used. An abstraction layer will be required which is present in the form of FileBrowserHelpers in [SimpleFileBrowser](https://github.com/yasirkula/UnitySimpleFileBrowser) plugin.

**Comment by achimmihca** [comment]
I would be happy with a folder selection dialog even if it is only for desktop platforms.

I expect this to be some kind of flag to the regular file selection dialog and thus pretty simple to implement.

**Comment by yasirkula** [comment]
This plugin doesn't support desktop platforms though.

**Comment by achimmihca** [comment]
I see. Guess this issue can be closed then as won't fix.
